<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UserAreaRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
            'city_id'   =>  'required',
            'area_id'   =>  'nullable',
        ];
    }
     public function messages()
     {

         return [
           'city_id'   =>   'This field is required.',
           'area_id'   =>   'This field is required.',
         ];
         return parent::messages(); // TODO: Change the autogenerated stub
     }
}
